services:
  #-----------------#
  # Frontend Service #
  #-----------------#
  - type: web
    name: affidavitai
    env: node
    plan: free
    rootDir: ./
    build_command: npm install
    start_command: node server.js
    envVars:
      - key: BACKEND_URL
        value: http://affidavit-backend:8000
      - key: MONGO_URL
        fromSecret: MONGO_URL_SECRET

  #-----------------#
  # Backend Service #
  #-----------------#
  - type: web
    name: affidavit-backend
    # Instruct Render to use a Docker environment
    env: docker
    plan: free
    # Specify the path to your Dockerfile
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /
    envVars:
      - key: OPENROUTER_API_KEY
        fromSecret: OPENROUTER_API_KEY_SECRET