services:
  #-----------------#
  # Frontend Service #
  #-----------------#
  - type: web
    name: affidavit-frontend
    env: node
    plan: free
    rootDir: ./
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: BACKEND_URL
        value: http://affidavit-backend:8000
      - key: MONGO_URL
        sync: false

  #-----------------#
  # Backend Service #
  #-----------------#
  - type: web
    name: affidavit-backend
    env: python
    plan: free
    rootDir: ./
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    healthCheckPath: /
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false