services:
  #-----------------#
  # Frontend Service #
  #-----------------#
  - type: web
    name: affidavit-frontend
    env: node
    plan: free
    rootDir: ./
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: BACKEND_URL
        value: http://affidavit-backend:8000
      # FIX: Define only the key for the secret
      - key: MONGO_URL

  #-----------------#
  # Backend Service #
  #-----------------#
  - type: web
    name: affidavit-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /
    envVars:
      # FIX: Define only the key for the secret
      - key: OPENROUTER_API_KEY